import test from 'node:test';
import assert from 'node:assert/strict';
import * as m from '../../src/next/model.ts';
const hash = 'sha256:' + 'a'.repeat(64);
for (const value of ['payments', 'nested/app', 'app-name_v2.0', 'a--b']) test(`repository accepts ${value}`, () => assert.equal(m.repository(value), value));
for (const value of ['', '../app', 'app/..', '/app', 'app//child', 'app;id', 'app\n', 'app\\child', '$(id)', 'App', 'a/%2e']) test(`repository rejects ${JSON.stringify(value)}`, () => assert.throws(() => m.repository(value)));
for (const value of ['demo', 'demo_user', 'demo-user']) test(`namespace accepts ${value}`, () => assert.equal(m.namespace(value), value));
for (const value of ['a/b', 'a.b', '+robot', 'a\n', 'a'.repeat(256)]) test(`namespace rejects ${JSON.stringify(value)}`, () => assert.throws(() => m.namespace(value)));
for (const value of [hash, 'sha512:' + 'f'.repeat(128)]) test(`supports ${value.slice(0, 7)}`, () => assert.equal(m.digest(value), value));
for (const value of ['sha256:short', 'sha256:' + 'a'.repeat(63), 'sha256:' + 'A'.repeat(64), 'md5:' + 'a'.repeat(32), hash + '\n', hash + ';id']) test(`digest rejects ${value.slice(0, 16)} ${value.length}`, () => assert.throws(() => m.digest(value)));
test('immutable command copies full validated digest', () => assert.equal(m.immutableCommand('quay.io', 'demo', 'nested/app', hash, 'podman'), `podman pull quay.io/demo/nested/app@${hash}`));
for (const host of ['https://quay.io', 'quay.io;id', 'user@quay.io', 'quay.io\n']) test(`command rejects host ${JSON.stringify(host)}`, () => assert.throws(() => m.immutableCommand(host, 'demo', 'app', hash, 'docker')));
test('unknown command tool rejected', () => assert.throws(() => m.immutableCommand('quay.io', 'demo', 'app', hash, 'sh')));
test('tag API uses page one and specificTag encoding', () => {
  const url = new URL(m.tagsPath('demo', 'nested/app', 1, 'v2.8.1'), 'https://quay.io');
  assert.equal(url.pathname, '/api/v1/repository/demo/nested/app/tag/');
  assert.equal(url.searchParams.get('page'), '1'); assert.equal(url.searchParams.get('specificTag'), 'v2.8.1');
});
for (const page of ['0', '-1', '1.2', 'Infinity', '1e2', '1000000']) test(`invalid page ${page}`, () => assert.throws(() => m.pageNumber(page)));
test('runtime rejects empty and inconsistent scope', () => {assert.throws(() => m.parseRuntime({mode: 'live', namespaces: []})); assert.throws(() => m.parseRuntime({mode: 'live', namespaces: ['demo'], repositories: ['other/app']}));});
test('runtime never consumes an arbitrary registry URL', () => assert.equal(m.parseRuntime({mode: 'live', namespaces: ['demo'], repositories: ['demo/app'], registry: 'attacker.invalid'}).registry, 'quay.io'));
test('unknown identity is not anonymous', () => {assert.throws(() => m.parseUser({})); assert.equal(m.parseUser({anonymous: true}), null); assert.equal(m.parseUser({anonymous: false, username: 'demo'}), 'demo');});
test('missing permission/visibility is not public', () => assert.equal(m.parseRepository({namespace: 'demo', name: 'app'}).visibility, 'Not reported'));
test('hostile metadata stays plain string data', () => assert.equal(m.parseRepository({namespace: 'demo', name: 'app', description: '<script>attack</script>'}).description, '<script>attack</script>'));
test('repository cursors remain opaque', () => assert.equal(m.parseRepositories({repositories: [], next_page: 'a+b/c==%'}).next, 'a+b/c==%'));
test('invalid repository list rejected rather than empty', () => assert.throws(() => m.parseRepositories({repositories: 'no'})));
test('tag parser preserves false sparse presence and unknown flags', () => {const tag = m.parseTags({page: 1, has_additional: false, tags: [{name: 'v1', manifest_digest: hash, child_manifests_presence: {[hash]: false}}]}).tags[0]; assert.equal(tag.presence[hash], false); assert.equal(tag.index, null); assert.equal(tag.immutable, null);});
test('tag parser does not pretend absent pagination fields exist', () => assert.throws(() => m.parseTags({tags: []})));
test('manifest kind and platforms parsed without aggregating download size', () => {const v = m.parseManifest({digest: hash, is_manifest_list: true, manifest_data: JSON.stringify({manifests: [{digest: hash, platform: {os: 'linux', architecture: 'arm64', variant: 'v8'}}]})}); assert.equal(v.platforms[0].label, 'linux/arm64/v8'); assert.equal(v.compressedBytes, null);});
test('malformed manifest does not render as empty', () => assert.throws(() => m.parseManifest({digest: hash, is_manifest_list: false, manifest_data: '{broken'})));
for (const [status, expected] of [['queued', 'pending'], ['failed', 'unavailable'], ['unsupported', 'unsupported'], ['manifest_layer_too_large', 'unsupported'], ['novel_state', 'unavailable']]) test(`scanner ${status} never clean`, () => {const result = m.parseScan({status}); assert.equal(result.state, expected); assert.notEqual(result.message, 'No vulnerabilities reported');});
test('scanned but missing report rejected', () => assert.throws(() => m.parseScan({status: 'scanned', data: null})));
test('malformed scanned features rejected', () => assert.throws(() => m.parseScan({status: 'scanned', data: {Layer: {Features: null}}})));
test('valid empty report is qualified, not safe', () => {const v = m.parseScan({status: 'scanned', data: {Layer: {Features: []}}}); assert.equal(v.message, 'No vulnerabilities reported'); assert.equal(v.state, 'reported');});
test('duplicate package advisory deduplicated and unsafe link removed', () => {
  const vuln = {Name: 'CVE-EXAMPLE', Severity: 'High', Link: 'javascript:alert(1)'};
  const v = m.parseScan({status: 'scanned', data: {Layer: {Features: [{Name: 'pkg', Version: '1', Vulnerabilities: [vuln, vuln]}]}}});
  assert.equal(v.findings.length, 1); assert.equal(v.findings[0].link, null); assert.equal(v.findings[0].fix, 'Not reported');
});
for (const value of ['javascript:alert(1)', 'data:text/html,hi', 'https://user:secret@example.com', 'https://example.com/\nsecret', 'http://example.com']) test(`unsafe navigation rejected ${JSON.stringify(value)}`, () => assert.equal(m.safeLink(value), null));
test('safe advisory HTTPS URL retained', () => assert.equal(m.safeLink('https://example.com/advisory'), 'https://example.com/advisory'));
for (const [width, root, forced, expected] of [[1152,16,false,'inline'],[1151,16,false,'page'],[2000,32,false,'page'],[3000,32,false,'inline'],[2000,16,true,'page'],[NaN,16,false,'page'],[2000,0,false,'page']]) test(`inspector ${width}/${root}/${forced}`, () => assert.equal(m.inspectorMode(width, root, forced), expected));
test('invalid timestamps are not fabricated', () => {assert.equal(m.formatDate(null), 'Not reported'); assert.equal(m.formatDate('garbage'), 'Not reported');});
